### ISSUE TITLE
ExecJS error

### ISSUE THREAD

**Issue by gazayas** [gazayas/hope#16]
Windows is throwing a ExecJS error.

Not sure what this is, but if this isn't fixed we probably can't move forward.

Kind of old and in Japanese, but [this post](http://qiita.com/scivola/items/ec7625118fcf6de5203a) might help

[this](https://www.oiax.jp/books/rails3book/coffee-script-type-error.html) seems pretty simple

[Here](https://github.com/twbs/bootstrap-sass/issues/696) is something in English

It might help to install node.js and restart the computer.
If that doesn't work, we can include the coffeescript gem

**Comment by gazayas** [comment]
Is hopefully fixed with [this commit](https://github.com/gazayas/hope/commit/5bf314f42a75f3075316924470c182865c45fd13) but needs to be double checked

**Comment by gazayas** [comment]
`bundle update coffee-script-source` didnt work

**Comment by gazayas** [comment]
had Carl install node.js

**Comment by gazayas** [comment]
It worked!!!!! 🎉 
Carl restarted his computer after installing node.js and now everythings fine

**Comment by crazypergy** [comment]
WE DID IT!
