### ISSUE TITLE
Check if Execjs was really the issue

### ISSUE THREAD

**Issue by gazayas** [gazayas/hope#19]
Because Node.js was installed and restarting the computer fixed that, I want to see if the other gems are needed.

@crazypergy, I'm assigning this to you

1. Go to the `Gemfile`
2. Delete these lines:
https://github.com/gazayas/hope/blob/bf8deb087943921abb7db29fd50f47b794b9a7c0/Gemfile#L24-L26
3. Run `bundle install` in the command prompt
4. See if the site works

Please do the same with this one too, not sure if this next line is needed either:
https://github.com/gazayas/hope/blob/bf8deb087943921abb7db29fd50f47b794b9a7c0/Gemfile#L64

よろしく

**Comment by crazypergy** [comment]
This is fixed.

**Comment by gazayas** [comment]
🎉
